In [1]:
##Normalization Problem
#Import numpy library to be able to use arrays
import numpy as np
#Create a placeholder 5x5 array
X = np.random.random((5,5))
#store the mean of array X to variable Y
Y = X.mean()
#store the standard deviation of array X to variable W
W = X.std()
#complete the normalization formula 
Z = (X-Y)/W
print(Z)
#save array Z using file name X_normalized'
np.save('X_normalized', Z)


[[ 0.16791916 -0.98121546  0.21408268  1.29815065  0.28890113]
 [ 0.95365796 -0.11780026  0.71147148  1.28817934 -0.32772647]
 [ 1.31279491  0.42075338  1.2842185  -1.33707917 -1.66995994]
 [-1.03164468 -1.8959627  -0.38270499  0.153238   -0.41278486]
 [ 1.01575641 -1.02162241  1.41636155 -0.00869136 -1.33829283]]


In [2]:
##DIVISIBLE BY 3 PROBLEM
#Import numpy library to be able to use arrays
import numpy as np
#Create a placeholder 5x5 array
a = np.zeros((10,10))
#create a for loop the creates a 10x10 array from 1 - 100
i = 1
for j in range(10):
    for k in range(10):
        a[j,k] = i
        i += 1
# squares the elements inside the array
a = a**2
# change the data type of the elements inside the array
b = a.astype(int)
#find all elements that are divisible by 3
modulo = b%3==0
#slices the only elements that are found 'True' by the modulo
div_by_3 = b[modulo]
print(div_by_3)
#save array using file name 'div_by_3'
np.save('div_by_3', div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
